// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace GestionDocs.Data.Abstraction.Models
{
    public partial class DocumentTransitionHistory
    {
        public Guid Id { get; set; }
        public Guid DocumentId { get; set; }
        public Guid? EmployeeId { get; set; }
        public string AllowedToEmployeeNames { get; set; }
        public DateTime? TransitionTime { get; set; }
        public long Order { get; set; }
        public DateTime? TransitionTimeForSort { get; set; }
        public string InitialState { get; set; }
        public string DestinationState { get; set; }
        public string Command { get; set; }

        public virtual Document Document { get; set; }
        public virtual Employee Employee { get; set; }
    }
}