// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace GestionDocs.Data.Abstraction.Models
{
    public partial class Document
    {
        public Document()
        {
            DocumentTransitionHistories = new HashSet<DocumentTransitionHistory>();
        }

        public Guid Id { get; set; }
        public int Number { get; set; }
        public string Name { get; set; }
        public string Comment { get; set; }
        public Guid AuthorId { get; set; }
        public Guid? ManagerId { get; set; }
        public decimal Sum { get; set; }
        public string State { get; set; }
        public string StateName { get; set; }

        public virtual Employee Author { get; set; }
        public virtual Employee Manager { get; set; }
        public virtual ICollection<DocumentTransitionHistory> DocumentTransitionHistories { get; set; }
    }
}