// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace GestionDocs.Data.Abstraction.Models
{
    public partial class Employee
    {
        public Employee()
        {
            DocumentAuthors = new HashSet<Document>();
            DocumentManagers = new HashSet<Document>();
            DocumentTransitionHistories = new HashSet<DocumentTransitionHistory>();
            EmployeeRoles = new HashSet<EmployeeRole>();
        }

        public Guid Id { get; set; }
        public string Name { get; set; }
        public Guid StructDivisionId { get; set; }
        public bool IsHead { get; set; }

        public virtual StructDivision StructDivision { get; set; }
        public virtual ICollection<Document> DocumentAuthors { get; set; }
        public virtual ICollection<Document> DocumentManagers { get; set; }
        public virtual ICollection<DocumentTransitionHistory> DocumentTransitionHistories { get; set; }
        public virtual ICollection<EmployeeRole> EmployeeRoles { get; set; }
    }
}