// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace GestionDocs.Data.Abstraction.Models
{
    public partial class Role
    {
        public Role()
        {
            EmployeeRoles = new HashSet<EmployeeRole>();
        }

        public Guid Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<EmployeeRole> EmployeeRoles { get; set; }
    }
}