// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace GestionDocs.Data.Abstraction.Models
{
    public partial class StructDivision
    {
        public StructDivision()
        {
            Employees = new HashSet<Employee>();
            InverseParent = new HashSet<StructDivision>();
        }

        public Guid Id { get; set; }
        public string Name { get; set; }
        public Guid? ParentId { get; set; }

        public virtual StructDivision Parent { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual ICollection<StructDivision> InverseParent { get; set; }
    }
}